[FRAME] Load document in frame preview 🪟
dotmind/blink pull request #74
Opened 2023-01-10 16:11 UTC by ValMgr

TODO: 

- [x] Create DrawerProvider & components
- [x] Split and clean Document and FilePreview components
- [ ] Add condition to display preview only on desktop
- [ ] Add preview on file upload
- [ ] Add button / link to copy file url from preview

2023-01-11 08:29 UTC, ValMgr commented
@bltnico Pour la width, j'ai augmenté le padding, mais pour que le drawer s'apdate dans le cas des pdf à l'horizontal (diapo etc..) je pense pas que mettre une width fixe sois conseillé.

2023-01-11 08:35 UTC, bltnico commented
> @bltnico Pour la width, j'ai augmenté le padding, mais pour que le drawer s'apdate dans le cas des pdf à l'horizontal (diapo etc..) je pense pas que mettre une width fixe sois conseillé.

Non je suis d'accord @ValMgr, il faut trouver un calcul mais dans l'idée on peut prendre un peu plus de place que sur la démo que tu m'as présenté hier

2023-01-11 10:11 UTC, bltnico reviewed
Remarques à prendre en compte pour la suite du dev ⚠️

2023-01-11 10:11 UTC, bltnico commented on src/app/providers/DrawerProvider.tsx
> +        setIsLoading(false);
Pourquoi faire ça, tu dupliques du code là non ?
Normalement dans la logique le provider du drawer ne doit rien faire de plus que gérer l'ouverture et fermeture basé sur une URL (qu'il faudra parser). Mais la récupération du document & co c'est déjà traité par le `DownloadProvider` (de tête, nom peut être pas exact)

2023-01-11 10:11 UTC, bltnico commented on src/app/components/History/index.tsx
> +  );
```suggestion
  const handleOpenPreview = useCallback(
    (url: string) => {
      open(url);
    },
    [open],
  );
```

Dans l'idée c'est mieux. On appelle juste une méthode pour ouvrir et c'est elle qui va set correctement l'url ainsi que check si c'est déjà ouvert ou pas au lieu de déporter la logique dans des composants qui techniquement, n'en ont rien à faire

2023-01-11 13:51 UTC, bltnico requested changes

2023-01-11 13:51 UTC, bltnico commented on src/app/components/Drawer/index.tsx
> +    }
Il ne faut pas attendre la fin du chargement pour afficher le drawer. Si le pdf est lourd, gros problème d'UX tu as l'impression que le click n'a pas été pris en compte. Il faut ouvrir au plus vite le drawer et ensuite rendre le document seulement quand lui il est chargé (et en profiter pour mettre le loader pour expliquer que ça arrive)

2023-01-11 13:51 UTC, bltnico commented on src/app/components/Drawer/index.tsx
> +  return render;
Si tu dois rendre juste un `useMemo`, autant faire un composant classique et par contre utiliser `React.memo` lors de l'export

2023-01-11 13:51 UTC, bltnico commented on src/app/components/Drawer/styles.module.scss
> +  max-width: 100vw;
```suggestion
  max-width: 80vw;
```
dans l'idée

2023-01-11 13:51 UTC, bltnico commented on src/app/components/Drawer/styles.module.scss
> +    border: none;
```suggestion
    border: none;
    background-color: rgba(255, 255, 255, 0.5);
    backdrop-filter: blur(3px);
```

Peut être ajouter un léger style sur l'overlay ?
+ cursor pointer pour comprendre qu'il a une intéraction

2023-01-11 13:51 UTC, bltnico commented on src/app/hooks/useWindowSize.ts
> +        width: window.outerWidth,
Pour corriger un problème ?

2023-01-11 13:51 UTC, bltnico commented on src/main.tsx
> +        <DownloadProvider>
Non ne pas déplacer le `DownloadProvider` si haut, on a pas besoin de soumettre toute l'app à lui. Il faut l'utiliser comme avant dans `Preview` et dans le `Drawer`

2023-01-11 13:51 UTC, bltnico commented on src/app/providers/DrawerProvider.tsx
> +  }, [setIsOpen, setIsClosing]);
Je suppose que le state `isClosing` c'est juste pour les animations ? Avec le `setTimeout` ce n'est pas le plus propre, peut être réfléchir à une alternative

2023-01-11 13:51 UTC, bltnico commented on src/modules/download/components/Document/index.tsx
> +  return renderDocument;
Pareil ici, tu retourne juste un `useMemo`

2023-01-11 13:51 UTC, bltnico commented on src/modules/download/providers/DownloadProvider.tsx
> +  const canDownload = useMemo(() => !!fingerprint && !!url, [fingerprint, url]);
Attention c'est un changement important.
Tu changes la logique du provider seulement pour répondre à la demande du Drawer, tu rends les deux dépendants. Ta méthode `canDownload` par défaut retournera `true` vu que tu donnes l'url courante par défaut.

La logique serait plutôt, je veux dl le document : 
- On initialise (passe en props) avec une URL, on parse, si possible on prend
- Il y a un argument ID dans l'url, je prends (comportement actuel)

2023-01-11 13:55 UTC, ValMgr commented on src/app/components/Drawer/index.tsx
> +    }
C'est pour ça que j'avais mis un cursor: progress pour que l'user comprennent qu'il se passe quelque choses

2023-01-11 13:59 UTC, ValMgr commented on src/app/components/Drawer/styles.module.scss
> +  max-width: 100vw;
Yes, mais c'est le composant <Document /> avec le pdf qui définis la taille du drawer. Si un document en paysage fais plus de 80vw il va overflow quand même.

2023-01-11 14:03 UTC, ValMgr commented on src/app/hooks/useWindowSize.ts
> +        width: window.outerWidth,
Yep, en mobile j'ai l'impression qu'il compte également les élements en overflow (Le drawer qui s'anime) et je me retrouve avec une width de 700 sur un mobile qui en fait 300. Et on utilise cette valeur pour set la width du document pdf

2023-01-11 14:14 UTC, ValMgr commented on src/modules/download/providers/DownloadProvider.tsx
> +  const canDownload = useMemo(() => !!fingerprint && !!url, [fingerprint, url]);
Hmm je suis pas sur de comprendre où le provider dépend du drawer ? 🤔

C'est le même provider utilisé sur la page preview qui n'as pas de drawer. 
L'url est initialement set avec le `window.location `(donc l'url courrante). Mais on ajoute une methode setUrl pour pouvoir la changer au besoin (dans le cas du drawer) mais ne le rend pas dépendant de cette méthode.

Après en effet la méthode `canDownload` est un peu usless mais servait jusqu'a présent juste à s'assurer que le fichier sois donwload qu'une seule fois.

2023-01-11 14:44 UTC, ValMgr commented on src/app/components/Drawer/index.tsx
> +    }
Car sinon l'autre solution et de remplacer le `<Document />` par un `<Loader />` pendant le chargement, mais une fois charger on à un flash lors du switch entre les deux composants que je trouve assez laid.

2023-01-11 15:02 UTC, bltnico commented on src/app/components/Drawer/index.tsx
> +    }
Comment on fait sur la page de `Preview` actuel ? J'avais vu le cursor mais trop subtile

2023-01-11 15:02 UTC, bltnico commented on src/app/components/Drawer/styles.module.scss
> +  max-width: 100vw;
Ah, bon en tout cas l'idée c'est pas de dépasser cette max width après qui doit stoper qui 🤷‍♂️

2023-01-11 15:03 UTC, bltnico commented on src/app/hooks/useWindowSize.ts
> +        width: window.outerWidth,
Le drawer n'existe pas en dehors de l'écran avant d'être ouvert, si ?

2023-01-11 15:14 UTC, ValMgr commented on src/app/hooks/useWindowSize.ts
> +        width: window.outerWidth,
Non, enfin juste les 350 millisecondes pendant lesquels il slide.

2023-01-11 15:30 UTC, bltnico commented on src/app/hooks/useWindowSize.ts
> +        width: window.outerWidth,
Et du coup ça te fait un problème sur mobile quand même, même pour 350ms ?

2023-01-12 08:47 UTC, ValMgr commented on src/app/components/Drawer/index.tsx
> +    }
Pareil, on à un loader. Sauf que si le pdf est plus large que le conteneur (Comme un A4 en paysage) on vois le conteneur s'élargir et c'est là que ça flash. Dans le cas d'un A4 portrait si la taille est bien adapté ça ne se vois pas trop.

Et du coups en ouvrant le drawer qu'une fois le document télécharger, le drawer à déjà sa taille définitive et il glitch pas lors de l'ouverture.

2023-01-12 08:51 UTC, bltnico commented on src/app/components/Drawer/index.tsx
> +    }
Je pense voir ce que tu veux dire 🤔 
Il doit bien y avoir une petite astuce, un truc d'UI pour faire ça smooth, à réfléchir si tu as des idées tu peux balancer sur Slack que l'on en parle en asynchrone

2023-01-12 14:10 UTC, bltnico reviewed
Quelques commentaires 👀

2023-01-12 14:10 UTC, bltnico commented on src/app/components/Drawer/index.tsx
> +import { useDownload } from '@/modules/download/providers/DownloadProvider';
Import ⬆️

2023-01-12 14:10 UTC, bltnico commented on src/app/pages/Home.tsx
> +        <DownloadProvider>
Tu ne peux pas mettre le `DownloadProvider` en parent que du `Drawer` ? Enfin en tout cas moins de composant que là

2023-01-12 14:10 UTC, bltnico commented on src/app/providers/DrawerProvider.tsx
> +  }, [setIsOpen, setIsClosing]);
Tu n'as rien trouvé d'autre du coup ?

2023-01-12 14:38 UTC, ValMgr commented on src/app/pages/Home.tsx
> +        <DownloadProvider>
Non car les autres composants on besoin du DrawerProvider pour l'ouvrir, et le DrawerProvider à besoin du DownloadProvider pour download la preview à l'ouverture

2023-01-12 14:45 UTC, ValMgr commented on src/app/providers/DrawerProvider.tsx
> +  }, [setIsOpen, setIsClosing]);
Non, à part installer des librairies externe qui gère les anims d'entrée et de sortie. 

Mais en plus j'imagine quelles font +/- là même choses, c'est juste délégué un truck dégueu à quelqu'un d'autre.

Sinon on pourrait faire un hook complet qui gère les anims mais juste pour une seule anim de slideOut je trouve ça un peu overkill ?

2023-01-12 14:56 UTC, bltnico commented on src/app/providers/DrawerProvider.tsx
> +  }, [setIsOpen, setIsClosing]);
Effectivement mais avec un [truc natif](https://developer.mozilla.org/en-US/docs/Web/API/Element/animationend_event) comme ça, pas OK ?

2023-01-12 14:56 UTC, bltnico commented on src/app/pages/Home.tsx
> +        <DownloadProvider>
Ah ouais bon...
Ça fait un peu chier en terme de propreté de code mais bon

2023-01-12 15:49 UTC, ValMgr commented on src/app/providers/DrawerProvider.tsx
> +  }, [setIsOpen, setIsClosing]);
Done

2023-01-12 16:09 UTC, bltnico approved these changes
👏

2023-01-12 16:10 UTC, bltnico commented
Ref https://github.com/dotmind/blink/pull/73

2023-01-12 16:42 UTC, merged